version: "3.9"

services:
  postgres:
    image: postgres:18
    container_name: NUTCS_RAW
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file:
      - .env
    ports:
      - "5050:80"
    depends_on:
      - postgres

  app:
    build: .
    container_name: sql_conv
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - .:/app
    command: ["python", "sql_conv.py"]

volumes:
  pg_data:
